### ISSUE TITLE
Clicking on opened fab wont close it

### ISSUE THREAD

**Issue by AliEasy** [Darshan0/floating_action_bubble#10]
The only way to close items is to click on them
the items wont disappear by clicking on fab

Also please update code sample
Thanks.

**Comment by ujjwalbe** [comment]
I'm also facing this same issue, looks like animation controller is not being triggered

**Comment by AliEasy** [comment]
@ujjwalbe 
Yes the code sample is fine. I know that now.
And as You said using `onPress: () => _animationController.isCompleted ? _animationController.reverse(): _animationController.forward(),` does the trick.
Thanks a lot
