### ISSUE TITLE
Button shadow

### ISSUE THREAD

**Issue by mirunamd** [Darshan0/floating_action_bubble#11]
Is there a way to disable the button's shadow?

<img width="62" alt="Screenshot 2020-11-16 at 14 29 36" src="https://user-images.githubusercontent.com/28065717/99257977-27621e80-2818-11eb-9b5f-bb55781d13b5.png">

**Comment by Darshan0** [comment]
@mirunamd the solution to this would be to set the elevation of the FIoatingActionBubble to 0dp but haven't used elevation attribute of the FloatingActionButton so there's no way right now. ill leverage all attributes of FloatingActionButton to FloatingActionBubble in the next release.

**Comment by mirunamd** [comment]
Thanks!
