### ISSUE TITLE
Multiple instances of FloatingActionBubble

### ISSUE THREAD

**Issue by simon01** [Darshan0/floating_action_bubble#2]
I am getting the following errors when two instances of FloatingActionBubble are used in my app. Is there anyway that we can set heroTag like we can do for FloatingActionButton?

> There are multiple heroes that share the same tag within a subtree.
> 
> Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
> In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
> Here is the subtree for one of the offending heroes: Hero

**Comment by Darshan0** [comment]
@simon01 , as of now there no implementation with a herotag, will include it in the next release.

**Comment by Darshan0** [comment]
@simon01 herotag has been implemented in the latest version 1.1.1

**Comment by simon01** [comment]
@Darshan0 Great... thanks
