### ISSUE TITLE
Dynamic fab animation

### ISSUE THREAD

**Issue by stact** [Darshan0/floating_action_bubble#6]
Hi,

I'm using the bubble fab on page viewer that display dynamically the fab (onpagechanged).

The standard fab is fading "normally" but with floating action bubble is appearing from another place.

Is it normal? How could we have a normal fade?

Screens below:

Floating action bubble
![bubble](https://user-images.githubusercontent.com/9899166/87228180-b14c3780-c39f-11ea-84ec-c411bc7c9775.gif)

Standard floating action button
![fab](https://user-images.githubusercontent.com/9899166/87228198-d2148d00-c39f-11ea-8a30-33b0400c52e4.gif)

**Comment by Darshan0** [comment]
Not aware of this behaviour. look like the hero tag as of now, there is no way to change it.
