### ISSUE TITLE
rtl Directionality Support

### ISSUE THREAD

**Issue by boinxi** [Darshan0/floating_action_bubble#8]
When surrounding a page with `Directionality(textDirection: TextDirection.rtl, ....`, the animation breaks down.
The still bubbles come from left to right and are being cut from the right.
![WhatsApp Image 2020-08-29 at 7 10 41 PM](https://user-images.githubusercontent.com/57293916/91641202-7b384500-ea2b-11ea-9b3c-1bf5f03dd862.jpeg)

**Comment by Darshan0** [comment]
Will support this in the next version. thank you

**Comment by tinlokcheung** [comment]
> When surrounding a page with `Directionality(textDirection: TextDirection.rtl, ....`, the animation breaks down.
> The still bubbles come from left to right and are being cut from the right.
> ![WhatsApp Image 2020-08-29 at 7 10 41 PM](https://user-images.githubusercontent.com/57293916/91641202-7b384500-ea2b-11ea-9b3c-1bf5f03dd862.jpeg)

Hi 
I'm a beginner on flutter
Just wondering how can you move the FAB at the left of screen? I want to move it to centre and have tried to modify "floatingActionButtonLocation"..but seems not working

Thanks mate

**Comment by AliEasy** [comment]
I do really need this feature right now :(

**Comment by Darshan0** [comment]
@AliEasy and @boinxi, rtl directionality is supported in version 1.1.2
